language: go

script:
- go vet ./...
- go test -v -race ./...

branches:
  only:
  - master

go:
  - 1.10
  - 1.11
  go get -u github.com/golang/lint/golint
  go get -u github.com/kisielk/errcheck
  go vet ./...
  go test -v ./...
  golint -set_exit_status ./...
  errcheck ./...
matrix:
  fast_finish: true
  include:
  - name: gofmt
    script: diff -u <(echo -n) <(gofmt -d -s .)
  - name: golint
    install: go get -u github.com/golang/lint/golint
    script: golint -set_exit_status ./...
  - name: errcheck
    install: go get -u github.com/kisielk/errcheck
    script: errcheck ./...
